### ISSUE TITLE
Key is inverted 

### ISSUE THREAD

**Issue by ghost** [hker9527/ChuniControl#1]
The key is inverted when pressed, but the light is matching, maybe 
`int index = Math.min(Math.max(0, (int) (x / d)), KEY_COUNT - 1);` 
need to be 
 `int index = 16 - Math.min(Math.max(0, (int) (x / d)), KEY_COUNT - 1);`

**Comment by hker9527** [comment]
Check if the orientation is right. Also, make sure you use my version of chuniio.

**Comment by ghost** [comment]
Closing because this is fixed in 2020.5.2 release
